"""Render spec-based tests and Hypothesis properties. No captured return values."""

from __future__ import annotations

import textwrap
from collections import defaultdict
from recoverage.models import Analysis


def render_drafts(analysis: Analysis) -> list[tuple[str, str]]:
    cases = [
        case
        for case in analysis.analytics.get("sbst", {}).get("cases", [])
        if not case.get("raised")
    ]
    properties = analysis.analytics.get("pbt", {}).get("properties", [])
    by_module: dict[str, list[dict]] = defaultdict(list)
    for case in cases:
        by_module[case["module"]].append(case)
    plans: list[tuple[str, str]] = []
    for module, grouped in sorted(by_module.items()):
        plans.append((_path(module, "recoverage"), _example_file(module, grouped)))
    prop_modules = {item["module"]: item for item in properties}
    for module, prop in sorted(prop_modules.items()):
        plans.append((_path(module, "recoverage_pbt"), _property_file(module, prop)))
    return plans


def _path(module: str, suffix: str) -> str:
    stem = module.split(".")[-1]
    return f"tests/test_{stem}_{suffix}.py"


def _example_file(module: str, cases: list[dict]) -> str:
    names = sorted({case["name"] for case in cases})
    specs = "\n".join(f"- {case['qualname']}: {case['spec']}" for case in cases)
    body = []
    for index, case in enumerate(cases, start=1):
        args = ", ".join(repr(value) for value in case["args"])
        check = _structural_assert(case.get("annotation") or "")
        body.append(
            textwrap.dedent(
                f'''\
                def test_{case["name"]}_spec_{index}():
                    """{case["spec"]}"""
                    result = {case["name"]}({args})
                    {check}
                '''
            ).rstrip()
        )
    return (
        '"""Generated by Recoverage.\n\n'
        "Tests are written against a signature spec, not against a captured return value.\n"
        "Recoverage will not overwrite this file.\n"
        f"{specs}\n"
        '"""\n\n'
        f"from {module} import {', '.join(names)}\n\n"
        + "\n\n".join(body)
        + "\n"
    )


def _structural_assert(annotation: str) -> str:
    lowered = annotation.lower()
    if "dict" in lowered:
        return 'assert isinstance(result, dict), "signature annotation is dict"'
    if "list" in lowered:
        return 'assert isinstance(result, list), "signature annotation is list"'
    if "bool" in lowered:
        return 'assert isinstance(result, bool), "signature annotation is bool"'
    if "float" in lowered or "int" in lowered:
        return 'assert isinstance(result, (int, float)) and not isinstance(result, bool), "signature annotation is numeric"'
    if "str" in lowered:
        return 'assert isinstance(result, str), "signature annotation is str"'
    return 'assert result is None or isinstance(result, (int, float, str, dict, list, tuple)), "signature has no tighter annotation"'


def _property_file(module: str, prop: dict) -> str:
    name = prop["symbol"].split(".")[-1]
    params = prop.get("parameters") or []
    strategies = ", ".join(_strategy(parameter) for parameter in params) or "st.none()"
    arg_names = ", ".join(params) if params else "unused"
    call = f"{name}({', '.join(params)})" if params else f"{name}()"
    return (
        '"""Generated by Recoverage.\n\n'
        "Property tests: structural conformance, determinism, and entity substitution.\n"
        "The in-process engine already evaluated at least 1000 inputs. This file uses a\n"
        "smaller Hypothesis budget so the suite stays reviewable.\n"
        '"""\n\n'
        "from hypothesis import given, settings, strategies as st\n\n"
        f"from {module} import {name}\n\n"
        "@settings(max_examples=25, database=None, deadline=None)\n"
        f"@given({strategies})\n"
        f"def test_{name}_properties({arg_names}):\n"
        "    try:\n"
        f"        first = {call}\n"
        f"        second = {call}\n"
        "    except (TypeError, ValueError, KeyError, OverflowError):\n"
        "        return\n"
        "    assert first == second\n"
        "    assert first is None or isinstance(first, (int, float, str, bool, dict, list, tuple))\n"
    )


def _strategy(name: str) -> str:
    if name in {"amount", "subtotal", "subtotal_amount", "price", "captured"}:
        return "st.floats(min_value=-5, max_value=1000, allow_nan=False, allow_infinity=False)"
    if name in {"units", "qty"}:
        return "st.integers(min_value=-2, max_value=120)"
    if name in {"authorized", "enabled", "flag"}:
        return "st.booleans()"
    if name in {"prices"}:
        return "st.lists(st.floats(min_value=-2, max_value=20, allow_nan=False, allow_infinity=False), max_size=4)"
    if name in {"method", "coupon", "tier", "token", "code"}:
        return 'st.sampled_from(["", "x", "card", "ach", "pro", "free", "SAVE10", "alice", "bob"])'
    return "st.one_of(st.none(), st.integers(min_value=-2, max_value=5), st.sampled_from([\"x\", \"alice\"]))"
