"""Render spec-based pytest files. Property drafts use a fixed sample, not Hypothesis. No captured return values."""

from __future__ import annotations

import textwrap
from collections import defaultdict
from recoverage.models import Analysis


def render_drafts(analysis: Analysis) -> list[tuple[str, str]]:
    cases = [
        case
        for case in analysis.analytics.get("sbst", {}).get("cases", [])
        if not case.get("raised")
    ]
    properties = analysis.analytics.get("pbt", {}).get("properties", [])
    by_module: dict[str, list[dict]] = defaultdict(list)
    for case in cases:
        by_module[case["module"]].append(case)
    plans: list[tuple[str, str]] = []
    for module, grouped in sorted(by_module.items()):
        plans.append((_path(module, "recoverage"), _example_file(module, grouped)))
    prop_modules = {item["module"]: item for item in properties}
    for module, prop in sorted(prop_modules.items()):
        plans.append((_path(module, "recoverage_pbt"), _property_file(module, prop)))
    return plans


def _path(module: str, suffix: str) -> str:
    stem = module.split(".")[-1]
    return f"tests/test_{stem}_{suffix}.py"


def _example_file(module: str, cases: list[dict]) -> str:
    names = sorted({case["name"] for case in cases})
    specs = "\n".join(f"- {case['qualname']}: {case['spec']}" for case in cases)
    body = []
    for index, case in enumerate(cases, start=1):
        args = ", ".join(repr(value) for value in case["args"])
        check = _structural_assert(case.get("annotation") or "")
        body.append(
            textwrap.dedent(
                f'''\
                def test_{case["name"]}_spec_{index}():
                    """{case["spec"]}"""
                    result = {case["name"]}({args})
                    {check}
                '''
            ).rstrip()
        )
    return (
        '"""Generated by Recoverage.\n\n'
        "Tests are written against a signature spec, not against a captured return value.\n"
        "Recoverage will not overwrite this file.\n"
        f"{specs}\n"
        '"""\n\n'
        f"from {module} import {', '.join(names)}\n\n"
        + "\n\n".join(body)
        + "\n"
    )


def _structural_assert(annotation: str) -> str:
    lowered = annotation.lower()
    if "dict" in lowered:
        return 'assert isinstance(result, dict), "signature annotation is dict"'
    if "list" in lowered:
        return 'assert isinstance(result, list), "signature annotation is list"'
    if "bool" in lowered:
        return 'assert isinstance(result, bool), "signature annotation is bool"'
    if "float" in lowered or "int" in lowered:
        return 'assert isinstance(result, (int, float)) and not isinstance(result, bool), "signature annotation is numeric"'
    if "str" in lowered:
        return 'assert isinstance(result, str), "signature annotation is str"'
    return 'assert result is None or isinstance(result, (int, float, str, dict, list, tuple)), "signature has no tighter annotation"'


def _property_file(module: str, prop: dict) -> str:
    name = prop["symbol"].split(".")[-1]
    params = prop.get("parameters") or []
    rows = ",\n".join(f"    ({', '.join(_sample_literal(parameter, index) for parameter in params)})" for index in range(4))
    if not params:
        rows = "    ()"
    return (
        '"""Generated by Recoverage.\n\n'
        "Property tests: structural conformance and determinism on a fixed sample.\n"
        "The in-process engine already evaluated the wider input space. This file stays\n"
        "runnable with pytest alone.\n"
        '"""\n\n'
        f"from {module} import {name}\n\n"
        f"_CASES = [\n{rows},\n]\n\n"
        f"def test_{name}_properties():\n"
        "    for args in _CASES:\n"
        "        try:\n"
        f"            first = {name}(*args)\n"
        f"            second = {name}(*args)\n"
        "        except (TypeError, ValueError, KeyError, OverflowError):\n"
        "            continue\n"
        "        assert first == second\n"
        "        assert first is None or isinstance(first, (int, float, str, bool, dict, list, tuple))\n"
    )


def _sample_literal(name: str, index: int) -> str:
    table = {
        "amount": ("1.0", "0.0", "-1.0", "1000.0"),
        "subtotal": ("10.0", "0.0", "-1.0", "50.0"),
        "subtotal_amount": ("10.0", "0.0", "-1.0", "50.0"),
        "price": ("1.0", "0.0", "-1.0", "20.0"),
        "captured": ("10.0", "1.0", "0.0", "100.0"),
        "units": ("1", "0", "-1", "3"),
        "qty": ("1", "0", "-1", "3"),
        "authorized": ("True", "False", "True", "False"),
        "enabled": ("True", "False", "True", "False"),
        "flag": ("True", "False", "True", "False"),
        "prices": ("[1.0, 2.0]", "[]", "[-1.0]", "[3.5]"),
        "method": ('"card"', '"ach"', '""', '"nope"'),
        "coupon": ('"SAVE10"', "None", '""', '"HALF"'),
        "tier": ('"pro"', '"free"', '""', '"pro"'),
        "token": ('"alice"', "None", '""', '"bob"'),
        "code": ('"SAVE10"', "None", '""', '"x"'),
    }
    choices = table.get(name)
    if choices is None:
        choices = ("None", "0", '"x"', "1")
    return choices[index % len(choices)]
